"""Data constants for the dining system.

Copyright © 2021-2025 Hoagie Club and affiliates.

Licensed under the MIT License. You may obtain a copy of the License at:

  https://github.com/hoagieclub/meal/blob/main/LICENSE

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

This software is provided "as-is", without warranty of any kind.
"""

MEAT_KEYWORDS = {
    "chicken",
    "beef",
    "pork",
    "lamb",
    "bacon",
    "ham",
    "turkey",
    "duck",
    "veal",
    "sausage",
    "pepperoni",
    "salami",
    "prosciutto",
    "chorizo",
    "bison",
    "venison",
    "goat",
    "mutton",
    "anchovy",
    "anchovies",
    "tuna",
    "salmon",
    "cod",
    "trout",
    "sardine",
    "sardines",
    "shrimp",
    "crab",
    "lobster",
    "clam",
    "clams",
    "oyster",
    "oysters",
    "mussel",
    "mussels",
    "scallop",
    "scallops",
    "crayfish",
    "squid",
    "octopus",
    "calamari",
    "caviar",
    "roe",
    "poultry",
    "meat",
    "game",
    "fish",
}

DAIRY_EGG_HONEY_KEYWORDS = {
    "milk",
    "cheese",
    "butter",
    "cream",
    "yogurt",
    "kefir",
    "ghee",
    "casein",
    "caseinate",
    "whey",
    "lactose",
    "egg",
    "eggs",
    "mayonnaise",
    "honey",
    "royal jelly",
    "beeswax",
}

HIDDEN_ANIMAL_KEYWORDS = {
    "gelatin",
    "lard",
    "tallow",
    "suet",
    "collagen",
    "cochineal",
    "carmine",
    "isinglass",
    "shellac",
    "rennet",
}

PORK_KEYWORDS = {
    "pork",
    "bacon",
    "ham",
    "lard",
    "gelatin",
    "pepperoni",
    "salami",
    "prosciutto",
    "chorizo",
    "pancetta",
}

NON_KOSHER_SEAFOOD_KEYWORDS = {
    "shrimp",
    "crab",
    "lobster",
    "clam",
    "clams",
    "oyster",
    "oysters",
    "mussel",
    "mussels",
    "scallop",
    "scallops",
    "crayfish",
    "squid",
    "octopus",
    "calamari",
    "catfish",
    "swordfish",
    "shark",
    "eel",
    "sturgeon",
}

ALCOHOL_KEYWORDS = {
    "alcohol",
    "wine",
    "beer",
    "lager",
    "ale",
    "stout",
    "cider",
    "brandy",
    "cognac",
    "rum",
    "whiskey",
    "whisky",
    "gin",
    "vodka",
    "tequila",
    "vermouth",
    "sherry",
    "port",
    "sake",
    "liqueur",
    "mead",
}

DINING_HALLS = {
    "Center for Jewish Life",
    "Forbes College",
    "Graduate College",
    "Mathey College",
    "Rockefeller College",
    "Whitman & Butler Colleges",
    "Yeh College & New College West",
}

DINING_CAFES = {
    "Atrium Cafe",
    "Cafe 701",
    "Cafe Vivian",
    "Chancellor Green Cafe",
    "Chemistry CaFe",
    "EQuad Cafe",
    "Frist Gallery",
    "Garden Room",
    "Genomics Cafe",
    "Meadows Cafe",
    "Mosaic Restaurant",
    "Sally Frank Cafe at Prospect House",
    "Shultz Cafe",
    "Studio 34",
    "Tiger Tea Room",
    "Witherspoon's",
}

SAMPLE_MENUS = [
    [
        {
            "id": "560112",
            "name": "European Style Breakfast Station",
            "description": "Allergens: Milk, Eggs",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560112",
        },
        {
            "id": "560102",
            "name": "Eggs Made to Order",
            "description": "Allergens: Eggs",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560102",
        },
        {
            "id": "560113",
            "name": "French Toast or Pancakes",
            "description": "Allergens: Milk, Eggs, Wheat, Gluten, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560113",
        },
        {
            "id": "560100",
            "name": "Omelet Bar with Pork Options",
            "description": "Allergens: Milk, Eggs",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560100",
        },
        {
            "id": "217001",
            "name": "Bagel Bar & Toppings",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=217001",
        },
        {
            "id": "280036",
            "name": "Oatmeal",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=280036",
        },
        {
            "id": "560115",
            "name": "O'Brien Potatoes",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560115",
        },
        {
            "id": "560114",
            "name": "Pork Sausage Patties",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560114",
        },
        {
            "id": "061002",
            "name": "Scrambled Eggs",
            "description": "Allergens: Eggs",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=061002",
        },
        {
            "id": "560111",
            "name": "Build your own yogurt parfait",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten, Ingredients include coconut, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560111",
        },
    ],
    [
        {
            "id": "020047",
            "name": "Manhattan Clam Chowder with Bacon",
            "description": "Allergens: Milk, Crustacean Shellfish, Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=020047",
        },
        {
            "id": "560317",
            "name": "Roasted Garlic and Potato Soup",
            "description": "Allergens: Milk",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560317",
        },
        {
            "id": "560750",
            "name": "Beef Hot Pot Stir Fry - Mala Xiang Guo",
            "description": "Allergens: Wheat, Soybeans, Gluten, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560750",
        },
        {
            "id": "141113",
            "name": "Organic Tofu & Vegetable LoMein",
            "description": "Allergens: Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=141113",
        },
        {
            "id": "560152",
            "name": "All Beef Hot Dog",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560152",
        },
        {
            "id": "560154",
            "name": "Beef & Mushroom Burger",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560154",
        },
        {
            "id": "603650",
            "name": "Beyond Burger",
            "description": "Allergens: Ingredients include coconut",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=603650",
        },
        {
            "id": "242005",
            "name": "Black Bean Burger",
            "description": "Allergens: Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=242005",
        },
        {
            "id": "560153",
            "name": "Chicken Cheesesteak",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560153",
        },
        {
            "id": "560155",
            "name": "Grilled Cheese",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560155",
        },
        {
            "id": "560156",
            "name": "Grilled Chicken Bar",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560156",
        },
        {
            "id": "560151",
            "name": "Steak Sandwich",
            "description": "Allergens: Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560151",
        },
        {
            "id": "560447",
            "name": "Shrimp in Chipotle Sauce",
            "description": "Allergens: Crustacean Shellfish, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560447",
        },
        {
            "id": "141170",
            "name": "Three Bean Taco Filling",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=141170",
        },
        {
            "id": "520204",
            "name": "Fried Plantains",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=520204",
        },
        {
            "id": "560448",
            "name": "Pasta with Sweet Corn, Tomato & Basil",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560448",
        },
        {
            "id": "560010",
            "name": "Spanish Rice",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560010",
        },
    ],
    [
        {
            "id": "520170",
            "name": "Chipotle Chicken Corn Chowder",
            "description": "Allergens: Milk",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=520170",
        },
        {
            "id": "560215",
            "name": "Chinese Eggplant with Hoisin",
            "description": "Allergens: Wheat, Soybeans, Sesame, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560215",
        },
        {
            "id": "560217",
            "name": "Kung Pao Chicken",
            "description": "Allergens: Soybeans",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560217",
        },
        {
            "id": "560152",
            "name": "All Beef Hot Dog",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560152",
        },
        {
            "id": "560154",
            "name": "Beef & Mushroom Burger",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560154",
        },
        {
            "id": "603650",
            "name": "Beyond Burger",
            "description": "Allergens: Ingredients include coconut",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=603650",
        },
        {
            "id": "242005",
            "name": "Black Bean Burger",
            "description": "Allergens: Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=242005",
        },
        {
            "id": "560153",
            "name": "Chicken Cheesesteak",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560153",
        },
        {
            "id": "560155",
            "name": "Grilled Cheese",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560155",
        },
        {
            "id": "560156",
            "name": "Grilled Chicken Bar",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560156",
        },
        {
            "id": "560151",
            "name": "Steak Sandwich",
            "description": "Allergens: Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560151",
        },
        {
            "id": "560143",
            "name": "Chicken Cacciatore",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560143",
        },
        {
            "id": "560793",
            "name": "Sicilian Braised Mushrooms + Tofu",
            "description": "Allergens: Soybeans, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560793",
        },
        {
            "id": "141376",
            "name": "Penne Pasta Marinara",
            "description": "Allergens: Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=141376",
        },
        {
            "id": "560458",
            "name": "Roasted Yukon Gold Potatoes",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560458",
        },
    ],
    [
        {
            "id": "560027",
            "name": "Basmati Rice",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560027",
        },
        {
            "id": "560789",
            "name": "Lemongrass Roast Chicken",
            "description": "Allergens: Soybeans",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560789",
        },
        {
            "id": "560790",
            "name": "Lemongrass Roast Tofu",
            "description": "Allergens: Soybeans",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560790",
        },
        {
            "id": "560709",
            "name": "Beef Bourguignon",
            "description": "Allergens: Milk, Wheat, Gluten, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560709",
        },
        {
            "id": "560710",
            "name": "Seitan Brisket",
            "description": "Allergens: Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560710",
        },
        {
            "id": "560647",
            "name": "Creamy Polenta",
            "description": "Allergens: Milk",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560647",
        },
        {
            "id": "560150",
            "name": "Onion Rings",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560150",
        },
        {
            "id": "560711",
            "name": "Pasta Primavera",
            "description": "Allergens: Milk, Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560711",
        },
        {
            "id": "560712",
            "name": "Roasted Butternut Squash",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560712",
        },
        {
            "id": "161064",
            "name": "Steakhouse Fries",
            "description": "Allergens: Soybeans",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=161064",
        },
    ],
    [
        {
            "id": "560786",
            "name": "Beef Gyudon (Japanese Beef)",
            "description": "Allergens: Soybeans, Sesame, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560786",
        },
        {
            "id": "560208",
            "name": "Vegan Fried Rice",
            "description": "Allergens: Soybeans",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560208",
        },
        {
            "id": "560621",
            "name": "Peruvian Roasted Chicken",
            "description": "Allergens: Milk, Soybeans, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560621",
        },
        {
            "id": "560065",
            "name": "Braised Seitan with Wild Mushrooms",
            "description": "Allergens: Wheat, Soybeans, Gluten, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560065",
        },
        {
            "id": "560047",
            "name": "Pasta with Pesto Cream Sauce",
            "description": "Allergens: Milk, Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560047",
        },
        {
            "id": "560483",
            "name": "Roasted Sweet Potatoes",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560483",
        },
        {
            "id": "560622",
            "name": "Sofrito Rice",
            "description": "Allergens: None",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560622",
        },
    ],
    [
        {
            "id": "560784",
            "name": "Sichuan Honey Glazed Shrimp",
            "description": "Allergens: Crustacean Shellfish",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560784",
        },
        {
            "id": "560785",
            "name": "Sichuan Honey Glazed Tofu",
            "description": "Allergens: Soybeans",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560785",
        },
        {
            "id": "510189",
            "name": "Chicken Parmesan",
            "description": "Allergens: Milk, Eggs, Wheat, Soybeans, Sesame, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=510189",
        },
        {
            "id": "532034",
            "name": 'Meatless Vegan "Meatballs"',
            "description": "Allergens: Wheat, Soybeans, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=532034",
        },
        {
            "id": "560708",
            "name": "Aglio e Olio Pasta",
            "description": "Allergens: Milk, Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560708",
        },
        {
            "id": "559913",
            "name": "Baked Ziti",
            "description": "Allergens: Milk, Eggs, Wheat, Gluten",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=559913",
        },
        {
            "id": "560150",
            "name": "Onion Rings",
            "description": "Allergens: Milk, Wheat, Soybeans, Gluten, Ingredients include alcohol",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=560150",
        },
        {
            "id": "161064",
            "name": "Steakhouse Fries",
            "description": "Allergens: Soybeans",
            "link": "http://menus.princeton.edu/dining/_Foodpro/online-menu/label.asp?RecNumAndPort=161064",
        },
    ],
]
