# Generated by Django 5.1.3 on 2026-01-03 23:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('auth0_id', models.CharField(blank=True, db_index=True, help_text='Auth0 ID', max_length=255, null=True, unique=True)),
                ('net_id', models.CharField(blank=True, db_index=True, help_text='University NetID', max_length=20, null=True, unique=True)),
                ('class_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningVenue',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('map_name', models.CharField(max_length=255)),
                ('database_id', models.PositiveIntegerField(help_text="API's location identifier", primary_key=True, serialize=False, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('building_name', models.CharField(max_length=255)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this dining hall is currently operational')),
                ('category_id', models.PositiveIntegerField(blank=True, help_text='The category ID of the dining venue', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dining_venues',
                'indexes': [models.Index(fields=['database_id'], name='dining_venu_databas_1bec1e_idx'), models.Index(fields=['name'], name='dining_venu_name_0fbd19_idx'), models.Index(fields=['category_id'], name='dining_venu_categor_3b2a33_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('api_id', models.PositiveIntegerField(help_text='Original menu item ID from the API', primary_key=True, serialize=False)),
                ('api_url', models.URLField(blank=True, max_length=500)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('serving_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=20)),
                ('calories', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('calories_from_fat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trans_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dietary_fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamin_d', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('dietary_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Raw dietary flags from source (e.g., icons on nutrition page)', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_items',
                'indexes': [models.Index(fields=['calories'], name='menu_items_calorie_0d0f7e_idx'), models.Index(fields=['protein'], name='menu_items_protein_13ae5e_idx'), models.Index(fields=['sodium'], name='menu_items_sodium_4d9f40_idx'), models.Index(fields=['api_id'], name='menu_items_api_id_3b751a_idx'), models.Index(fields=['name'], name='menu_items_name_1ab05b_idx'), models.Index(fields=['api_url'], name='menu_items_api_url_5cb6e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('meal', models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner')], db_index=True, max_length=2)),
                ('dining_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='hoagiemeal.diningvenue')),
                ('menu_items', models.ManyToManyField(related_name='menus', to='hoagiemeal.menuitem')),
            ],
            options={
                'db_table': 'menus',
                'indexes': [models.Index(fields=['dining_venue', 'date', 'meal'], name='menus_dining__a52da7_idx')],
                'unique_together': {('dining_venue', 'date', 'meal')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('view_count', models.PositiveSmallIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('favorited', models.BooleanField(default=False)),
                ('saved_for_later', models.BooleanField(default=False)),
                ('would_eat_again', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], default='M', max_length=1, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='hoagiemeal.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='hoagiemeal__user_id_59b292_idx'), models.Index(fields=['menu_item'], name='hoagiemeal__menu_it_f361fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'menu_item'), name='user_menu_item_interaction')],
            },
        ),
        migrations.CreateModel(
            name='MenuItemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('average_like_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('saved_for_later_count', models.PositiveIntegerField(default=0)),
                ('would_eat_again_yes', models.PositiveIntegerField(default=0)),
                ('would_eat_again_no', models.PositiveIntegerField(default=0)),
                ('would_eat_again_maybe', models.PositiveIntegerField(default=0)),
                ('average_would_eat_again_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='hoagiemeal.menuitem')),
            ],
            options={
                'db_table': 'menu_item_metrics',
                'unique_together': {('menu_item',)},
            },
        ),
    ]
