# Generated by Django 5.1.3 on 2025-12-21 03:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api_id', models.PositiveIntegerField(help_text='Original menu item ID from the API', unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('dietary_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Raw dietary flags from source (e.g., icons on nutrition page)', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('auth0_id', models.CharField(blank=True, db_index=True, help_text='Auth0 ID', max_length=255, null=True, unique=True)),
                ('net_id', models.CharField(blank=True, db_index=True, help_text='University NetID', max_length=20, null=True, unique=True)),
                ('class_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningVenue',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('map_name', models.CharField(max_length=255)),
                ('database_id', models.PositiveIntegerField(help_text="API's location identifier", primary_key=True, serialize=False, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('building_name', models.CharField(max_length=255)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this dining hall is currently operational')),
                ('operation_hours', models.JSONField(blank=True, help_text='Operating hours in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dining_venues',
                'indexes': [models.Index(fields=['database_id'], name='dining_venu_databas_1bec1e_idx'), models.Index(fields=['name'], name='dining_venu_name_0fbd19_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restrictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of dietary restrictions/preferences', size=None)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of allergens', size=None)),
                ('dining_halls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of visible dining halls', size=None)),
                ('daily_calorie_target', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('daily_protein_target', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('show_nutrition', models.BooleanField(default=True, help_text='Show nutrition information')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dietary_profiles',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('meal', models.CharField(choices=[('BR', 'Breakfast'), ('LU', 'Lunch'), ('DI', 'Dinner')], db_index=True, max_length=2)),
                ('last_fetched', models.DateTimeField(auto_now=True, help_text='Last time menu was updated from API')),
                ('dining_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='hoagiemeal.diningvenue')),
                ('menu_items', models.ManyToManyField(related_name='menus', to='hoagiemeal.menuitem')),
            ],
            options={
                'db_table': 'menus',
                'indexes': [models.Index(fields=['dining_venue', 'date', 'meal'], name='menus_dining__a52da7_idx')],
                'unique_together': {('dining_venue', 'date', 'meal')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(help_text='Menu item that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hoagiemeal.menuitem')),
                ('user', models.ForeignKey(help_text='User who favorited the menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_item_favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='menu_item_f_user_id_022d01_idx'), models.Index(fields=['menu_item'], name='menu_item_f_menu_it_79bef2_idx'), models.Index(fields=['created_at'], name='menu_item_f_created_31b257_idx'), models.Index(fields=['user', 'created_at'], name='menu_item_f_user_id_04125a_idx')],
                'unique_together': {('user', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MP', 'Menu Page'), ('NP', 'Nutrition Page'), ('DM', 'Details Modal'), ('SR', 'Search Results'), ('OT', 'Other')], db_index=True, default='OT', help_text='Where the like came from', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(help_text='Menu item that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hoagiemeal.menuitem')),
                ('user', models.ForeignKey(help_text='User who liked the menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_item_likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='menu_item_l_user_id_89acc6_idx'), models.Index(fields=['menu_item'], name='menu_item_l_menu_it_6ba0b9_idx'), models.Index(fields=['source'], name='menu_item_l_source_ce9ef4_idx'), models.Index(fields=['created_at'], name='menu_item_l_created_2457b4_idx'), models.Index(fields=['user', 'menu_item'], name='menu_item_l_user_id_cb6ede_idx')],
                'unique_together': {('user', 'menu_item', 'source')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(blank=True, max_length=50)),
                ('serving_unit', models.CharField(blank=True, max_length=20)),
                ('calories', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('calories_from_fat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trans_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dietary_fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamin_d', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_info', to='hoagiemeal.menuitem')),
            ],
            options={
                'db_table': 'menu_item_nutrients',
                'indexes': [models.Index(fields=['calories'], name='menu_item_n_calorie_cb3891_idx'), models.Index(fields=['protein'], name='menu_item_n_protein_834583_idx')],
            },
        ),
    ]
