# Generated by Django 5.1.3 on 2026-02-06 06:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='ResidentialMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('meal', models.CharField(choices=[('BRE', 'Breakfast'), ('LUN', 'Lunch'), ('DIN', 'Dinner'), ('BRU', 'Brunch')], db_index=True, max_length=3)),
                ('menu_items', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'residential_menus',
            },
        ),
        migrations.CreateModel(
            name='RetailMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('menu_items', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'retail_menus',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('auth0_id', models.CharField(blank=True, db_index=True, help_text='Auth0 ID', max_length=255, null=True, unique=True)),
                ('net_id', models.CharField(blank=True, db_index=True, help_text='University NetID', max_length=20, null=True, unique=True)),
                ('class_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiningLocation',
            fields=[
                ('id', models.CharField(help_text="API's location identifier", max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='The category ID of the dining venue', max_length=50)),
                ('name', models.CharField(help_text='The name of the dining venue', max_length=255)),
                ('url', models.URLField(help_text='The URL of the dining venue', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dining_locations',
                'indexes': [models.Index(fields=['id'], name='dining_loca_id_cb21bb_idx'), models.Index(fields=['category'], name='dining_loca_categor_f77bcb_idx'), models.Index(fields=['name'], name='dining_loca_name_f9a3cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItemNutrition',
            fields=[
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition', serialize=False, to='hoagiemeal.menuitem')),
                ('servings_per_container', models.FloatField(blank=True, null=True)),
                ('serving_size', models.CharField(blank=True, max_length=50)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('total_fat', models.FloatField(blank=True, null=True)),
                ('total_fat_dv', models.FloatField(blank=True, null=True)),
                ('saturated_fat', models.FloatField(blank=True, null=True)),
                ('saturated_fat_dv', models.FloatField(blank=True, null=True)),
                ('trans_fat', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('cholesterol_dv', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('sodium_dv', models.FloatField(blank=True, null=True)),
                ('total_carbs', models.FloatField(blank=True, null=True)),
                ('total_carbs_dv', models.FloatField(blank=True, null=True)),
                ('dietary_fiber', models.FloatField(blank=True, null=True)),
                ('dietary_fiber_dv', models.FloatField(blank=True, null=True)),
                ('total_sugars', models.FloatField(blank=True, null=True)),
                ('added_sugars', models.FloatField(blank=True, null=True)),
                ('added_sugars_dv', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('protein_dv', models.FloatField(blank=True, null=True)),
                ('vitamin_d', models.FloatField(blank=True, null=True)),
                ('vitamin_d_dv', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('calcium_dv', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('iron_dv', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('potassium_dv', models.FloatField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('allergens', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'menu_item_nutrition',
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['id'], name='menu_items_id_0634c3_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='menu_items_name_1ab05b_idx'),
        ),
        migrations.AddField(
            model_name='residentialmenu',
            name='dining_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_menus', to='hoagiemeal.dininglocation'),
        ),
        migrations.AddField(
            model_name='retailmenu',
            name='dining_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_menus', to='hoagiemeal.dininglocation'),
        ),
        migrations.AddIndex(
            model_name='menuitemnutrition',
            index=models.Index(fields=['menu_item'], name='menu_item_n_menu_it_8c746d_idx'),
        ),
        migrations.AddIndex(
            model_name='residentialmenu',
            index=models.Index(fields=['dining_location', 'date', 'meal'], name='residential_dining__4030de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='residentialmenu',
            unique_together={('dining_location', 'date', 'meal')},
        ),
        migrations.AddIndex(
            model_name='retailmenu',
            index=models.Index(fields=['dining_location', 'date'], name='retail_menu_dining__22ef3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retailmenu',
            unique_together={('dining_location', 'date')},
        ),
    ]
