# Generated by Django 5.1.3 on 2025-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningvenue',
            name='operation_hours',
        ),
        migrations.AddField(
            model_name='diningvenue',
            name='category_id',
            field=models.PositiveIntegerField(blank=True, help_text='Category ID from the API', null=True),
        ),
    ]
