# Generated by Django 5.1.3 on 2026-04-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFoodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('food', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'free_food_alerts',
                'indexes': [models.Index(fields=['email_id'], name='free_food_a_email_i_8b3f04_idx'), models.Index(fields=['start_time'], name='free_food_a_start_t_75fc6e_idx')],
            },
        ),
    ]
