# Generated by Django 5.1.3 on 2026-02-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialmenu',
            name='meal',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
