# Generated by Django 5.1.3 on 2025-08-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdietaryprofile',
            old_name='preferred_dining_halls',
            new_name='preferred_dining_venues',
        ),
    ]
