# Generated by Django 5.1.3 on 2026-01-05 08:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0002_remove_menuitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemNutrition',
            fields=[
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition', serialize=False, to='hoagiemeal.menuitem')),
                ('serving_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=20)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories_from_fat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trans_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dietary_fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vitamin_d', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_item_nutrition',
            },
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_calorie_0d0f7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_protein_13ae5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_sodium_4d9f40_idx',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='calories_from_fat',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='cholesterol',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='dietary_fiber',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='serving_unit',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sugars',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='total_carbohydrates',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='trans_fat',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='vitamin_d',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dietary_flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddIndex(
            model_name='menuitemnutrition',
            index=models.Index(fields=['menu_item'], name='menu_item_n_menu_it_8c746d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemnutrition',
            unique_together={('menu_item',)},
        ),
    ]
