# Generated by Django 5.1.3 on 2026-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0002_alter_residentialmenu_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemnutrition',
            name='serving_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
