# Generated by Django 5.1.3 on 2025-12-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0002_remove_diningvenue_operation_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningvenue',
            name='category_id',
        ),
    ]
