# Generated by Django 5.1.3 on 2025-08-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0002_rename_preferred_dining_halls_userdietaryprofile_preferred_dining_venues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdietaryprofile',
            name='preferred_dining_venues',
        ),
    ]
