# Generated by Django 5.1.3 on 2026-02-11 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0003_alter_menuitemnutrition_serving_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('view_count', models.PositiveSmallIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('favorited', models.BooleanField(default=False)),
                ('saved_for_later', models.BooleanField(default=False)),
                ('would_eat_again', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='hoagiemeal.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='hoagiemeal__user_id_59b292_idx'), models.Index(fields=['menu_item'], name='hoagiemeal__menu_it_f361fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'menu_item'), name='user_menu_item_interaction')],
            },
        ),
        migrations.CreateModel(
            name='MenuItemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('average_like_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('saved_for_later_count', models.PositiveIntegerField(default=0)),
                ('would_eat_again_yes', models.PositiveIntegerField(default=0)),
                ('would_eat_again_no', models.PositiveIntegerField(default=0)),
                ('would_eat_again_maybe', models.PositiveIntegerField(default=0)),
                ('average_would_eat_again_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='hoagiemeal.menuitem')),
            ],
            options={
                'db_table': 'menu_item_metrics',
                'unique_together': {('menu_item',)},
            },
        ),
        migrations.CreateModel(
            name='MenuItemSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('menu_item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hoagiemeal.menuitem')),
                ('menu_item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hoagiemeal.menuitem')),
            ],
            options={
                'indexes': [models.Index(fields=['menu_item_a', 'menu_item_b'], name='hoagiemeal__menu_it_053a46_idx')],
                'unique_together': {('menu_item_a', 'menu_item_b')},
            },
        ),
    ]
