# Generated by Django 5.1.3 on 2025-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0003_remove_userdietaryprofile_preferred_dining_venues'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menu',
            name='menus_dining__9d8f78_idx',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='dining_hall',
            new_name='dining_venue',
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('dining_venue', 'date', 'meal')},
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['dining_venue', 'date', 'meal'], name='menus_dining__a52da7_idx'),
        ),
    ]
