# Generated by Django 5.1.3 on 2025-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0003_remove_diningvenue_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningvenue',
            name='category_id',
            field=models.PositiveIntegerField(blank=True, help_text='The category ID of the dining venue', null=True),
        ),
    ]
