# Generated by Django 5.1.3 on 2026-02-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0004_menuiteminteraction_menuitemmetrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuiteminteraction',
            name='first_viewed_at',
        ),
        migrations.RemoveField(
            model_name='menuiteminteraction',
            name='last_viewed_at',
        ),
        migrations.RemoveField(
            model_name='menuiteminteraction',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='menuiteminteraction',
            name='viewed',
        ),
    ]
