# Generated by Django 5.1.3 on 2026-01-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0004_alter_menuitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hoagiemeal.menuitem')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hoagiemeal.menuitem')),
            ],
            options={
                'indexes': [models.Index(fields=['item_a', 'item_b'], name='hoagiemeal__item_a__d18103_idx')],
                'unique_together': {('item_a', 'item_b')},
            },
        ),
    ]
