# Generated by Django 5.1.3 on 2025-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0004_remove_menu_menus_dining__9d8f78_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningvenue',
            name='id',
        ),
        migrations.AlterField(
            model_name='diningvenue',
            name='database_id',
            field=models.PositiveIntegerField(help_text="API's location identifier", primary_key=True, serialize=False, unique=True),
        ),
    ]
