# Generated by Django 5.1.3 on 2025-12-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0004_diningvenue_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemnutrient',
            name='menu_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='hoagiemeal.menuitem'),
        ),
        migrations.AddIndex(
            model_name='diningvenue',
            index=models.Index(fields=['category_id'], name='dining_venu_categor_3b2a33_idx'),
        ),
    ]
