# Generated by Django 5.1.3 on 2025-10-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0005_remove_diningvenue_id_alter_diningvenue_database_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(related_name='menus', to='hoagiemeal.menuitem'),
        ),
    ]
