# Generated by Django 5.1.3 on 2026-01-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0005_menuitemsimilarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuiteminteraction',
            name='would_eat_again',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')], max_length=1, null=True),
        ),
    ]
