# Generated by Django 5.1.3 on 2025-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0005_alter_menuitemnutrient_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemnutrient',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
