# Generated by Django 5.1.3 on 2025-10-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0006_remove_menuitem_menu_menu_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth0_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auth0 ID', max_length=255, null=True, unique=True),
        ),
    ]
