# Generated by Django 5.1.3 on 2026-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0006_alter_menuiteminteraction_would_eat_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemnutrition',
            name='serving_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
