# Generated by Django 5.1.3 on 2025-10-25 00:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0007_customuser_auth0_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allergens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of allergens', size=None),
        ),
    ]
