# Generated by Django 5.1.3 on 2026-01-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0007_alter_menuitemnutrition_serving_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningvenue',
            name='category_id',
            field=models.CharField(blank=True, help_text='The category ID of the dining venue', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diningvenue',
            name='database_id',
            field=models.CharField(help_text="API's location identifier", max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='api_id',
            field=models.CharField(help_text='Original menu item ID from the API', max_length=50, primary_key=True, serialize=False),
        ),
    ]
