# Generated by Django 5.1.3 on 2025-10-25 00:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0008_customuser_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dining_halls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of visible dining halls', size=None),
        ),
    ]
