# Generated by Django 5.1.3 on 2025-12-12 04:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0010_add_dietary_fields_safe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'menu_item_bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'menu_item_upvotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='bookmarked_menu_items',
            field=models.ManyToManyField(related_name='bookmarked_by', to='hoagiemeal.menuitem'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upvoted_menu_items',
            field=models.ManyToManyField(related_name='upvoted_by', to='hoagiemeal.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='bookmark_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached number of bookmarks for this menu item'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached number of upvotes for this menu item'),
        ),
        migrations.AddField(
            model_name='menuitembookmark',
            name='menu_item',
            field=models.ForeignKey(help_text='Menu item that was bookmarked', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='hoagiemeal.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitembookmark',
            name='user',
            field=models.ForeignKey(help_text='User who bookmarked the menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitemupvote',
            name='menu_item',
            field=models.ForeignKey(help_text='Menu item that was upvoted', on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='hoagiemeal.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitemupvote',
            name='user',
            field=models.ForeignKey(help_text='User who upvoted the menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='menuitembookmark',
            index=models.Index(fields=['user'], name='menu_item_b_user_id_18c06f_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitembookmark',
            index=models.Index(fields=['menu_item'], name='menu_item_b_menu_it_66236c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitembookmark',
            index=models.Index(fields=['created_at'], name='menu_item_b_created_f7968c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitembookmark',
            unique_together={('user', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='menuitemupvote',
            index=models.Index(fields=['user'], name='menu_item_u_user_id_76f19c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemupvote',
            index=models.Index(fields=['menu_item'], name='menu_item_u_menu_it_ca6644_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemupvote',
            index=models.Index(fields=['created_at'], name='menu_item_u_created_da67a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemupvote',
            unique_together={('user', 'menu_item')},
        ),
    ]
