# Generated by Django 5.1.3 on 2025-12-12 06:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0011_menuitembookmark_menuitemupvote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bookmarked_menu_items',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='upvoted_menu_items',
        ),
    ]
