# Generated by Django 5.1.3 on 2025-12-18 03:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0012_remove_customuser_bookmarked_menu_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_nutrition',
            field=models.BooleanField(default=True, help_text='Show nutrition information'),
        ),
    ]
