# Generated by Django 5.1.3 on 2025-12-19 04:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0013_customuser_show_nutrition_menuitem_dietary_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dietary_flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Raw dietary flags from source (e.g., icons on nutrition page)', size=None),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_halal',
            field=models.BooleanField(db_index=True, default=False, help_text='Determined from ingredients/allergens'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_kosher',
            field=models.BooleanField(db_index=True, default=False, help_text='Determined from ingredients/allergens'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegan',
            field=models.BooleanField(db_index=True, default=False, help_text='Determined from ingredients/allergens'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(db_index=True, default=False, help_text='Determined from ingredients/allergens'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_vegetarian'], name='menu_items_is_vege_e6b0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_vegan'], name='menu_items_is_vega_7f2ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_halal'], name='menu_items_is_hala_11ea7a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_kosher'], name='menu_items_is_kosh_79b974_idx'),
        ),
    ]
