# Generated by Django 5.1.3 on 2025-12-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0014_menuitem_dietary_flags_menuitem_is_halal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BanditModel',
        ),
        migrations.DeleteModel(
            name='ExplanationTemplate',
        ),
        migrations.RemoveField(
            model_name='recommendationaction',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='recommendationaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendationfeedback',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='recommendationexplanation',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='uservector',
            name='user',
        ),
        migrations.DeleteModel(
            name='FoodVector',
        ),
        migrations.DeleteModel(
            name='RecommendationFeedback',
        ),
        migrations.DeleteModel(
            name='RecommendationAction',
        ),
        migrations.DeleteModel(
            name='RecommendationExplanation',
        ),
        migrations.DeleteModel(
            name='UserVector',
        ),
    ]
