# Generated by Django 5.1.3 on 2025-12-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0015_delete_banditmodel_delete_explanationtemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermeallog',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='usermeallog',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyGoalProgress',
        ),
        migrations.DeleteModel(
            name='UserGoal',
        ),
        migrations.DeleteModel(
            name='UserMealLog',
        ),
    ]
