# Generated by Django 5.1.3 on 2025-12-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0016_remove_usergoal_user_remove_usermeallog_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermealplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='SwipeTransactionIndividual',
        ),
        migrations.DeleteModel(
            name='UserMealPlan',
        ),
    ]
