# Generated by Django 5.1.3 on 2025-12-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0017_remove_usermealplan_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferencesnapshot',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstreak',
            name='user',
        ),
        migrations.DeleteModel(
            name='PreferenceChangeEvent',
        ),
        migrations.DeleteModel(
            name='UserPreferenceSnapshot',
        ),
        migrations.DeleteModel(
            name='UserStreak',
        ),
    ]
