# Generated by Django 5.1.3 on 2025-12-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0018_remove_userpreferencesnapshot_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipetransactionmarketplace',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='swipeoffer',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='swipeoffer',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='swipetransactionmarketplace',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='swipetransactionmarketplace',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='swipetransactionmarketplace',
            name='seller',
        ),
        migrations.DeleteModel(
            name='SwipeListing',
        ),
        migrations.DeleteModel(
            name='SwipeOffer',
        ),
        migrations.DeleteModel(
            name='SwipeTransactionMarketplace',
        ),
    ]
