# Generated by Django 5.1.3 on 2025-12-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0019_remove_swipetransactionmarketplace_listing_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuiteminterest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuiteminterest',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='socialrecommendation',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='socialrecommendation',
            name='source_user',
        ),
        migrations.RemoveField(
            model_name='socialrecommendation',
            name='target_user',
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.DeleteModel(
            name='InterestNode',
        ),
        migrations.DeleteModel(
            name='MenuItemInterest',
        ),
        migrations.DeleteModel(
            name='SocialRecommendation',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
