# Generated by Django 5.1.3 on 2025-12-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0021_remove_experimentmetriclog_experiment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
