# Generated by Django 5.1.3 on 2025-12-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0022_remove_userachievement_achievement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitembookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuitembookmark',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='menuitembookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menuitemmetrics',
            name='menu_item',
        ),
        migrations.AlterUniqueTogether(
            name='menuitemupvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuitemupvote',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='menuitemupvote',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='menurating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menurating',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='menurating',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_name_1ab05b_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_api_id_3b751a_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_is_vege_e6b0a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_is_vega_7f2ec2_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_is_hala_11ea7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='menu_items_is_kosh_79b974_idx',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='bookmark_count',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_halal',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_kosher',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='upvote_count',
        ),
        migrations.DeleteModel(
            name='MenuItemBookmark',
        ),
        migrations.DeleteModel(
            name='MenuItemMetrics',
        ),
        migrations.DeleteModel(
            name='MenuItemUpvote',
        ),
        migrations.DeleteModel(
            name='MenuRating',
        ),
    ]
