# Generated by Django 5.1.3 on 2025-12-19 04:50

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0023_alter_menuitembookmark_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='daily_calorie_target',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='daily_protein_target',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dining_halls',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_nutrition',
        ),
        migrations.RemoveField(
            model_name='userdietaryprofile',
            name='cuisine_preferences',
        ),
        migrations.RemoveField(
            model_name='userdietaryprofile',
            name='excluded_ingredients',
        ),
        migrations.RemoveField(
            model_name='userdietaryprofile',
            name='favorite_menu_items',
        ),
        migrations.RemoveField(
            model_name='userdietaryprofile',
            name='meal_time_preferences',
        ),
        migrations.RemoveField(
            model_name='userdietaryprofile',
            name='sustainability_preference',
        ),
        migrations.AddField(
            model_name='userdietaryprofile',
            name='allergens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of allergens', size=None),
        ),
        migrations.AddField(
            model_name='userdietaryprofile',
            name='daily_calorie_target',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='userdietaryprofile',
            name='daily_protein_target',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='userdietaryprofile',
            name='dietary_restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of dietary restrictions/preferences', size=None),
        ),
        migrations.AddField(
            model_name='userdietaryprofile',
            name='dining_halls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of visible dining halls', size=None),
        ),
        migrations.AddField(
            model_name='userdietaryprofile',
            name='show_nutrition',
            field=models.BooleanField(default=True, help_text='Show nutrition information'),
        ),
    ]
