# Generated by Django 5.1.3 on 2025-12-19 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0024_remove_customuser_allergens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(help_text='Menu item that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hoagiemeal.menuitem')),
                ('user', models.ForeignKey(help_text='User who favorited the menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_item_favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='menu_item_f_user_id_022d01_idx'), models.Index(fields=['menu_item'], name='menu_item_f_menu_it_79bef2_idx'), models.Index(fields=['created_at'], name='menu_item_f_created_31b257_idx'), models.Index(fields=['user', 'created_at'], name='menu_item_f_user_id_04125a_idx')],
                'unique_together': {('user', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='MenuItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MP', 'Menu Page'), ('NP', 'Nutrition Page'), ('DM', 'Details Modal'), ('SR', 'Search Results'), ('OT', 'Other')], db_index=True, default='OT', help_text='Where the like came from', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(help_text='Menu item that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hoagiemeal.menuitem')),
                ('user', models.ForeignKey(help_text='User who liked the menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_item_likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='menu_item_l_user_id_89acc6_idx'), models.Index(fields=['menu_item'], name='menu_item_l_menu_it_6ba0b9_idx'), models.Index(fields=['source'], name='menu_item_l_source_ce9ef4_idx'), models.Index(fields=['created_at'], name='menu_item_l_created_2457b4_idx'), models.Index(fields=['user', 'menu_item'], name='menu_item_l_user_id_cb6ede_idx')],
                'unique_together': {('user', 'menu_item', 'source')},
            },
        ),
    ]
