# Generated by Django 5.1.3 on 2025-12-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoagiemeal', '0025_menuitemfavorite_menuitemlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDietaryProfile',
            new_name='UserProfile',
        ),
    ]
